/** A name is always a de/en pair so switching language never changes the round. */
export type Phrase = { de: string; en: string }

/**
 * A word plus the imposter's hint. `near` is a neighbour of the word, and the
 * distance is the whole design: a clue about the neighbour almost always fits
 * the word too, but the neighbour is never the word, never a part of it and
 * never a synonym — so it hands over a direction to bluff in, not the answer.
 *
 * The band is the one party games call "medium": Wolf/Fuchs, Bier/Most,
 * Tennis/Badminton. One step closer (Frosch/Kröte, Espresso/Kaffee) and the
 * imposter may as well have been dealt the card; one step further
 * (Wüste/Strand) and the hint says nothing the category did not.
 *
 * Two rules the test in scripts/rules.mjs enforces, because breaking either
 * quietly ruins a round: `near` is never the word itself, and never another
 * word of the same category — that would let the imposter cross one off.
 */
export type Word = Phrase & { near: Phrase }

export type Category = {
  id: string
  name: Phrase
  emoji: string
  words: Word[]
}

export const CATEGORIES: Category[] = [
  {
    id: 'animals',
    emoji: '🦊',
    name: { de: 'Tiere', en: 'Animals' },
    words: [
      { de: 'Elefant', en: 'Elephant', near: { de: 'Nashorn', en: 'Rhino' } },
      { de: 'Pinguin', en: 'Penguin', near: { de: 'Robbe', en: 'Seal' } },
      { de: 'Krokodil', en: 'Crocodile', near: { de: 'Waran', en: 'Monitor lizard' } },
      { de: 'Eichhörnchen', en: 'Squirrel', near: { de: 'Marder', en: 'Marten' } },
      { de: 'Hai', en: 'Shark', near: { de: 'Rochen', en: 'Ray' } },
      { de: 'Igel', en: 'Hedgehog', near: { de: 'Maulwurf', en: 'Mole' } },
      { de: 'Kamel', en: 'Camel', near: { de: 'Lama', en: 'Llama' } },
      { de: 'Adler', en: 'Eagle', near: { de: 'Falke', en: 'Falcon' } },
      { de: 'Qualle', en: 'Jellyfish', near: { de: 'Seestern', en: 'Starfish' } },
      { de: 'Fledermaus', en: 'Bat', near: { de: 'Eule', en: 'Owl' } },
      { de: 'Schnecke', en: 'Snail', near: { de: 'Regenwurm', en: 'Earthworm' } },
      { de: 'Wolf', en: 'Wolf', near: { de: 'Fuchs', en: 'Fox' } },
      { de: 'Papagei', en: 'Parrot', near: { de: 'Kanarienvogel', en: 'Canary' } },
      { de: 'Biene', en: 'Bee', near: { de: 'Schmetterling', en: 'Butterfly' } },
      { de: 'Faultier', en: 'Sloth', near: { de: 'Koala', en: 'Koala' } },
      { de: 'Oktopus', en: 'Octopus', near: { de: 'Hummer', en: 'Lobster' } },
      { de: 'Pferd', en: 'Horse', near: { de: 'Esel', en: 'Donkey' } },
      { de: 'Ameise', en: 'Ant', near: { de: 'Termite', en: 'Termite' } },
      { de: 'Eisbär', en: 'Polar bear', near: { de: 'Walross', en: 'Walrus' } },
      { de: 'Frosch', en: 'Frog', near: { de: 'Molch', en: 'Newt' } },
    ],
  },
  {
    id: 'food',
    emoji: '🍕',
    name: { de: 'Essen & Trinken', en: 'Food & Drink' },
    words: [
      { de: 'Pizza', en: 'Pizza', near: { de: 'Lasagne', en: 'Lasagne' } },
      { de: 'Schnitzel', en: 'Schnitzel', near: { de: 'Gulasch', en: 'Goulash' } },
      { de: 'Sushi', en: 'Sushi', near: { de: 'Frühlingsrolle', en: 'Spring roll' } },
      { de: 'Kaugummi', en: 'Chewing gum', near: { de: 'Lutscher', en: 'Lollipop' } },
      { de: 'Espresso', en: 'Espresso', near: { de: 'Kakao', en: 'Cocoa' } },
      { de: 'Popcorn', en: 'Popcorn', near: { de: 'Chips', en: 'Crisps' } },
      { de: 'Suppe', en: 'Soup', near: { de: 'Salat', en: 'Salad' } },
      { de: 'Senf', en: 'Mustard', near: { de: 'Mayonnaise', en: 'Mayonnaise' } },
      { de: 'Wassermelone', en: 'Watermelon', near: { de: 'Ananas', en: 'Pineapple' } },
      { de: 'Käse', en: 'Cheese', near: { de: 'Butter', en: 'Butter' } },
      { de: 'Pommes', en: 'Fries', near: { de: 'Kroketten', en: 'Croquettes' } },
      { de: 'Honig', en: 'Honey', near: { de: 'Marmelade', en: 'Jam' } },
      { de: 'Zimt', en: 'Cinnamon', near: { de: 'Vanille', en: 'Vanilla' } },
      { de: 'Bier', en: 'Beer', near: { de: 'Most', en: 'Cider' } },
      { de: 'Spaghetti', en: 'Spaghetti', near: { de: 'Reis', en: 'Rice' } },
      { de: 'Erdbeere', en: 'Strawberry', near: { de: 'Kirsche', en: 'Cherry' } },
      { de: 'Toastbrot', en: 'Toast', near: { de: 'Semmel', en: 'Bread roll' } },
      { de: 'Chili', en: 'Chili', near: { de: 'Pfeffer', en: 'Pepper' } },
      { de: 'Eiswürfel', en: 'Ice cube', near: { de: 'Strohhalm', en: 'Drinking straw' } },
      { de: 'Apfelstrudel', en: 'Apple strudel', near: { de: 'Palatschinke', en: 'Crêpe' } },
    ],
  },
  {
    id: 'sports',
    emoji: '⚽',
    name: { de: 'Sport', en: 'Sports' },
    words: [
      { de: 'Fußball', en: 'Football', near: { de: 'Handball', en: 'Handball' } },
      { de: 'Klettern', en: 'Climbing', near: { de: 'Wandern', en: 'Hiking' } },
      { de: 'Yoga', en: 'Yoga', near: { de: 'Pilates', en: 'Pilates' } },
      { de: 'Marathon', en: 'Marathon', near: { de: 'Triathlon', en: 'Triathlon' } },
      { de: 'Skifahren', en: 'Skiing', near: { de: 'Snowboarden', en: 'Snowboarding' } },
      { de: 'Boxen', en: 'Boxing', near: { de: 'Judo', en: 'Judo' } },
      { de: 'Tauchen', en: 'Diving', near: { de: 'Segeln', en: 'Sailing' } },
      { de: 'Golf', en: 'Golf', near: { de: 'Bowling', en: 'Bowling' } },
      { de: 'Turnen', en: 'Gymnastics', near: { de: 'Ballett', en: 'Ballet' } },
      { de: 'Radrennen', en: 'Bike race', near: { de: 'Autorennen', en: 'Car race' } },
      { de: 'Schach', en: 'Chess', near: { de: 'Poker', en: 'Poker' } },
      { de: 'Surfen', en: 'Surfing', near: { de: 'Wasserski', en: 'Water skiing' } },
      { de: 'Eishockey', en: 'Ice hockey', near: { de: 'Eiskunstlauf', en: 'Figure skating' } },
      { de: 'Tennis', en: 'Tennis', near: { de: 'Badminton', en: 'Badminton' } },
      { de: 'Bogenschießen', en: 'Archery', near: { de: 'Darts', en: 'Darts' } },
      { de: 'Handstand', en: 'Handstand', near: { de: 'Purzelbaum', en: 'Somersault' } },
      { de: 'Stabhochsprung', en: 'Pole vault', near: { de: 'Weitsprung', en: 'Long jump' } },
      { de: 'Schiedsrichter', en: 'Referee', near: { de: 'Trainer', en: 'Coach' } },
      { de: 'Trainingslager', en: 'Training camp', near: { de: 'Turnier', en: 'Tournament' } },
      { de: 'Hantel', en: 'Dumbbell', near: { de: 'Laufband', en: 'Treadmill' } },
    ],
  },
  {
    id: 'screen',
    emoji: '🎬',
    name: { de: 'Filme & Serien', en: 'Movies & Shows' },
    words: [
      { de: 'Titanic', en: 'Titanic', near: { de: 'Pearl Harbor', en: 'Pearl Harbor' } },
      { de: 'Harry Potter', en: 'Harry Potter', near: { de: 'Narnia', en: 'Narnia' } },
      { de: 'Der Pate', en: 'The Godfather', near: { de: 'Scarface', en: 'Scarface' } },
      { de: 'Jurassic Park', en: 'Jurassic Park', near: { de: 'King Kong', en: 'King Kong' } },
      {
        de: 'Der König der Löwen',
        en: 'The Lion King',
        near: { de: 'Das Dschungelbuch', en: 'The Jungle Book' },
      },
      { de: 'Matrix', en: 'The Matrix', near: { de: 'Inception', en: 'Inception' } },
      { de: 'Stranger Things', en: 'Stranger Things', near: { de: 'Dark', en: 'Dark' } },
      { de: 'Breaking Bad', en: 'Breaking Bad', near: { de: 'Narcos', en: 'Narcos' } },
      {
        de: 'Findet Nemo',
        en: 'Finding Nemo',
        near: { de: 'Arielle', en: 'The Little Mermaid' },
      },
      {
        de: 'James Bond',
        en: 'James Bond',
        near: { de: 'Mission Impossible', en: 'Mission Impossible' },
      },
      {
        de: 'Herr der Ringe',
        en: 'Lord of the Rings',
        near: { de: 'Der Zauberer von Oz', en: 'The Wizard of Oz' },
      },
      { de: 'Tatort', en: 'Crime scene show', near: { de: 'Soko', en: 'Detective series' } },
      {
        de: 'Zurück in die Zukunft',
        en: 'Back to the Future',
        near: { de: 'Men in Black', en: 'Men in Black' },
      },
      { de: 'Game of Thrones', en: 'Game of Thrones', near: { de: 'Vikings', en: 'Vikings' } },
      { de: 'Shrek', en: 'Shrek', near: { de: 'Madagascar', en: 'Madagascar' } },
      { de: 'Star Wars', en: 'Star Wars', near: { de: 'Star Trek', en: 'Star Trek' } },
      { de: 'Die Simpsons', en: 'The Simpsons', near: { de: 'Family Guy', en: 'Family Guy' } },
      {
        de: 'Fluch der Karibik',
        en: 'Pirates of the Caribbean',
        near: { de: 'Die Schatzinsel', en: 'Treasure Island' },
      },
      { de: 'Avatar', en: 'Avatar', near: { de: 'Dune', en: 'Dune' } },
      { de: 'Sissi', en: 'Sissi', near: { de: 'Vom Winde verweht', en: 'Gone with the Wind' } },
    ],
  },
  {
    id: 'jobs',
    emoji: '👩‍🚒',
    name: { de: 'Berufe', en: 'Jobs' },
    words: [
      {
        de: 'Feuerwehrmann',
        en: 'Firefighter',
        near: { de: 'Rettungssanitäter', en: 'Paramedic' },
      },
      { de: 'Zahnarzt', en: 'Dentist', near: { de: 'Augenarzt', en: 'Eye doctor' } },
      { de: 'Pilot', en: 'Pilot', near: { de: 'Kapitän', en: 'Ship captain' } },
      { de: 'Bäcker', en: 'Baker', near: { de: 'Metzger', en: 'Butcher' } },
      {
        de: 'Lehrerin',
        en: 'Teacher',
        near: { de: 'Kindergärtnerin', en: 'Kindergarten teacher' },
      },
      { de: 'Influencer', en: 'Influencer', near: { de: 'Moderator', en: 'TV host' } },
      { de: 'Tierarzt', en: 'Vet', near: { de: 'Bauer', en: 'Farmer' } },
      { de: 'Programmierer', en: 'Programmer', near: { de: 'Ingenieur', en: 'Engineer' } },
      { de: 'Fotografin', en: 'Photographer', near: { de: 'Malerin', en: 'Painter' } },
      { de: 'Bauarbeiter', en: 'Construction worker', near: { de: 'Dachdecker', en: 'Roofer' } },
      { de: 'Kellner', en: 'Waiter', near: { de: 'Barkeeper', en: 'Bartender' } },
      { de: 'Bergführer', en: 'Mountain guide', near: { de: 'Skilehrer', en: 'Ski instructor' } },
      { de: 'Richterin', en: 'Judge', near: { de: 'Anwältin', en: 'Lawyer' } },
      { de: 'Astronaut', en: 'Astronaut', near: { de: 'Tiefseetaucher', en: 'Deep-sea diver' } },
      { de: 'Friseur', en: 'Hairdresser', near: { de: 'Kosmetikerin', en: 'Beautician' } },
      {
        de: 'Müllabfuhr',
        en: 'Garbage collector',
        near: { de: 'Straßenkehrer', en: 'Street sweeper' },
      },
      {
        de: 'Physiotherapeut',
        en: 'Physiotherapist',
        near: { de: 'Krankenpfleger', en: 'Nurse' },
      },
      { de: 'Detektiv', en: 'Detective', near: { de: 'Polizist', en: 'Police officer' } },
      { de: 'Steuerberater', en: 'Tax advisor', near: { de: 'Notar', en: 'Notary' } },
      { de: 'Busfahrerin', en: 'Bus driver', near: { de: 'Taxifahrer', en: 'Taxi driver' } },
    ],
  },
  {
    id: 'places',
    emoji: '🗺️',
    name: { de: 'Orte', en: 'Places' },
    words: [
      { de: 'Flughafen', en: 'Airport', near: { de: 'Hafen', en: 'Harbour' } },
      { de: 'Bibliothek', en: 'Library', near: { de: 'Buchhandlung', en: 'Bookshop' } },
      { de: 'Schwimmbad', en: 'Swimming pool', near: { de: 'Therme', en: 'Thermal spa' } },
      { de: 'Friedhof', en: 'Cemetery', near: { de: 'Kirche', en: 'Church' } },
      { de: 'Supermarkt', en: 'Supermarket', near: { de: 'Drogerie', en: 'Drugstore' } },
      { de: 'Zahnarztpraxis', en: 'Dental practice', near: { de: 'Apotheke', en: 'Pharmacy' } },
      { de: 'Baustelle', en: 'Construction site', near: { de: 'Werkstatt', en: 'Workshop' } },
      { de: 'Kino', en: 'Cinema', near: { de: 'Theater', en: 'Theatre' } },
      { de: 'Wüste', en: 'Desert', near: { de: 'Steppe', en: 'Steppe' } },
      { de: 'Autobahn', en: 'Motorway', near: { de: 'Tunnel', en: 'Tunnel' } },
      { de: 'Dachboden', en: 'Attic', near: { de: 'Keller', en: 'Basement' } },
      { de: 'Zirkus', en: 'Circus', near: { de: 'Jahrmarkt', en: 'Funfair' } },
      { de: 'Bahnhof', en: 'Train station', near: { de: 'Bushaltestelle', en: 'Bus stop' } },
      { de: 'Skihütte', en: 'Ski lodge', near: { de: 'Seilbahn', en: 'Cable car' } },
      { de: 'Gefängnis', en: 'Prison', near: { de: 'Kaserne', en: 'Barracks' } },
      { de: 'Museum', en: 'Museum', near: { de: 'Galerie', en: 'Art gallery' } },
      { de: 'Waschsalon', en: 'Laundromat', near: { de: 'Reinigung', en: 'Dry cleaner' } },
      { de: 'Leuchtturm', en: 'Lighthouse', near: { de: 'Windmühle', en: 'Windmill' } },
      { de: 'Fitnessstudio', en: 'Gym', near: { de: 'Turnhalle', en: 'Sports hall' } },
      {
        de: 'Weltraumstation',
        en: 'Space station',
        near: { de: 'Forschungsstation', en: 'Research station' },
      },
    ],
  },
  {
    id: 'objects',
    emoji: '🧦',
    name: { de: 'Alltag', en: 'Everyday Objects' },
    words: [
      { de: 'Regenschirm', en: 'Umbrella', near: { de: 'Gummistiefel', en: 'Rubber boots' } },
      { de: 'Zahnbürste', en: 'Toothbrush', near: { de: 'Kamm', en: 'Comb' } },
      { de: 'Staubsauger', en: 'Vacuum cleaner', near: { de: 'Besen', en: 'Broom' } },
      { de: 'Schlüsselbund', en: 'Keychain', near: { de: 'Geldbörse', en: 'Wallet' } },
      { de: 'Waschmaschine', en: 'Washing machine', near: { de: 'Kühlschrank', en: 'Fridge' } },
      { de: 'Kopfhörer', en: 'Headphones', near: { de: 'Lautsprecher', en: 'Speaker' } },
      { de: 'Klopapier', en: 'Toilet paper', near: { de: 'Küchenrolle', en: 'Paper towel' } },
      { de: 'Ladekabel', en: 'Charging cable', near: { de: 'Steckdose', en: 'Power socket' } },
      { de: 'Kerze', en: 'Candle', near: { de: 'Streichholz', en: 'Match' } },
      { de: 'Brille', en: 'Glasses', near: { de: 'Hörgerät', en: 'Hearing aid' } },
      { de: 'Wecker', en: 'Alarm clock', near: { de: 'Kalender', en: 'Calendar' } },
      { de: 'Socke', en: 'Sock', near: { de: 'Handschuh', en: 'Glove' } },
      { de: 'Geschirrspüler', en: 'Dishwasher', near: { de: 'Spülbecken', en: 'Kitchen sink' } },
      { de: 'Leiter', en: 'Ladder', near: { de: 'Hocker', en: 'Stool' } },
      { de: 'Spiegel', en: 'Mirror', near: { de: 'Fenster', en: 'Window' } },
      { de: 'Bügeleisen', en: 'Iron', near: { de: 'Wäscheleine', en: 'Clothesline' } },
      { de: 'Rucksack', en: 'Backpack', near: { de: 'Koffer', en: 'Suitcase' } },
      { de: 'Taschenlampe', en: 'Flashlight', near: { de: 'Feuerzeug', en: 'Lighter' } },
      { de: 'Schere', en: 'Scissors', near: { de: 'Klebeband', en: 'Tape' } },
      { de: 'Gießkanne', en: 'Watering can', near: { de: 'Blumentopf', en: 'Flowerpot' } },
    ],
  },
  {
    id: 'nature',
    emoji: '🌿',
    name: { de: 'Natur & Wetter', en: 'Nature & Weather' },
    words: [
      { de: 'Gewitter', en: 'Thunderstorm', near: { de: 'Sturm', en: 'Storm' } },
      { de: 'Regenbogen', en: 'Rainbow', near: { de: 'Morgenrot', en: 'Red sky at dawn' } },
      { de: 'Vulkan', en: 'Volcano', near: { de: 'Geysir', en: 'Geyser' } },
      { de: 'Nebel', en: 'Fog', near: { de: 'Raureif', en: 'Hoarfrost' } },
      { de: 'Lawine', en: 'Avalanche', near: { de: 'Mure', en: 'Mudslide' } },
      { de: 'Wasserfall', en: 'Waterfall', near: { de: 'Stromschnelle', en: 'Rapids' } },
      { de: 'Sonnenuntergang', en: 'Sunset', near: { de: 'Sonnenaufgang', en: 'Sunrise' } },
      { de: 'Gletscher', en: 'Glacier', near: { de: 'Eisberg', en: 'Iceberg' } },
      { de: 'Sandstrand', en: 'Sandy beach', near: { de: 'Düne', en: 'Sand dune' } },
      { de: 'Hagel', en: 'Hail', near: { de: 'Schneeregen', en: 'Sleet' } },
      { de: 'Vollmond', en: 'Full moon', near: { de: 'Sternschnuppe', en: 'Shooting star' } },
      { de: 'Dschungel', en: 'Jungle', near: { de: 'Mangrove', en: 'Mangrove' } },
      { de: 'Erdbeben', en: 'Earthquake', near: { de: 'Flutwelle', en: 'Tidal wave' } },
      { de: 'Tautropfen', en: 'Dewdrop', near: { de: 'Spinnennetz', en: 'Spiderweb' } },
      { de: 'Nordlicht', en: 'Northern lights', near: { de: 'Sternenhimmel', en: 'Starry sky' } },
      { de: 'Sumpf', en: 'Swamp', near: { de: 'Teich', en: 'Pond' } },
      { de: 'Höhle', en: 'Cave', near: { de: 'Schlucht', en: 'Gorge' } },
      { de: 'Windstille', en: 'Dead calm', near: { de: 'Hitzewelle', en: 'Heatwave' } },
      { de: 'Waldbrand', en: 'Wildfire', near: { de: 'Dürre', en: 'Drought' } },
      { de: 'Schneeflocke', en: 'Snowflake', near: { de: 'Eiszapfen', en: 'Icicle' } },
    ],
  },
  {
    id: 'austria',
    emoji: '🏔️',
    name: { de: 'Österreich', en: 'Austria' },
    words: [
      { de: 'Sachertorte', en: 'Sachertorte', near: { de: 'Cremeschnitte', en: 'Cream slice' } },
      {
        de: 'Lipizzaner',
        en: 'Lipizzaner horse',
        near: { de: 'Haflinger', en: 'Haflinger horse' },
      },
      {
        de: 'Wiener Riesenrad',
        en: 'Vienna Ferris wheel',
        near: { de: 'Stephansdom', en: "St. Stephen's Cathedral" },
      },
      { de: 'Großglockner', en: 'Großglockner', near: { de: 'Dachstein', en: 'Dachstein' } },
      { de: 'Lederhose', en: 'Lederhosen', near: { de: 'Dirndl', en: 'Dirndl' } },
      { de: 'Almdudler', en: 'Almdudler', near: { de: 'Radler', en: 'Shandy' } },
      { de: 'Schladming', en: 'Schladming', near: { de: 'Kitzbühel', en: 'Kitzbühel' } },
      {
        de: 'Mozartkugel',
        en: 'Mozart ball',
        near: { de: 'Manner-Schnitte', en: 'Manner wafer' },
      },
      { de: 'Heuriger', en: 'Wine tavern', near: { de: 'Gasthaus', en: 'Inn' } },
      {
        de: 'Kaiserschmarrn',
        en: 'Kaiserschmarrn',
        near: { de: 'Germknödel', en: 'Sweet yeast dumpling' },
      },
      { de: 'Wiener Linien', en: 'Vienna metro', near: { de: 'ÖBB', en: 'Austrian Railways' } },
      {
        de: 'Neujahrskonzert',
        en: 'New Year Concert',
        near: { de: 'Opernball', en: 'Opera Ball' },
      },
      { de: 'Krampus', en: 'Krampus', near: { de: 'Nikolaus', en: 'Saint Nicholas' } },
      { de: 'Wachau', en: 'Wachau valley', near: { de: 'Südsteiermark', en: 'Southern Styria' } },
      { de: 'Skisprungschanze', en: 'Ski jump', near: { de: 'Bobbahn', en: 'Bobsleigh track' } },
      { de: 'Schönbrunn', en: 'Schönbrunn Palace', near: { de: 'Hofburg', en: 'Hofburg' } },
      {
        de: 'Marillenknödel',
        en: 'Apricot dumpling',
        near: { de: 'Topfenknödel', en: 'Curd dumpling' },
      },
      {
        de: 'Bundesheer',
        en: 'Austrian army',
        near: { de: 'Zivildienst', en: 'Civilian service' },
      },
      { de: 'Kaffeehaus', en: 'Coffee house', near: { de: 'Konditorei', en: 'Patisserie' } },
      { de: 'Murinsel', en: 'Mur island', near: { de: 'Donauinsel', en: 'Danube Island' } },
    ],
  },
  {
    id: 'music',
    emoji: '🎧',
    name: { de: 'Musik', en: 'Music' },
    words: [
      { de: 'Schlagzeug', en: 'Drum kit', near: { de: 'Bass', en: 'Bass guitar' } },
      { de: 'Dudelsack', en: 'Bagpipes', near: { de: 'Akkordeon', en: 'Accordion' } },
      { de: 'Karaoke', en: 'Karaoke', near: { de: 'Talentshow', en: 'Talent show' } },
      { de: 'Festival', en: 'Festival', near: { de: 'Stadiontour', en: 'Stadium tour' } },
      { de: 'Ohrwurm', en: 'Earworm', near: { de: 'Refrain', en: 'Chorus' } },
      { de: 'Chor', en: 'Choir', near: { de: 'Orchester', en: 'Orchestra' } },
      { de: 'Techno', en: 'Techno', near: { de: 'Hip-Hop', en: 'Hip-hop' } },
      { de: 'Geige', en: 'Violin', near: { de: 'Cello', en: 'Cello' } },
      {
        de: 'Plattenspieler',
        en: 'Record player',
        near: { de: 'Kassettenrekorder', en: 'Cassette player' },
      },
      { de: 'Blasmusik', en: 'Brass band', near: { de: 'Volksmusik', en: 'Folk music' } },
      { de: 'Rapbattle', en: 'Rap battle', near: { de: 'Poetry Slam', en: 'Poetry slam' } },
      { de: 'Klavierstunde', en: 'Piano lesson', near: { de: 'Nachhilfe', en: 'Tutoring' } },
      {
        de: 'Kopfhörerkabel',
        en: 'Headphone cable',
        near: { de: 'Verstärker', en: 'Amplifier' },
      },
      { de: 'Gitarrensolo', en: 'Guitar solo', near: { de: 'Zugabe', en: 'Encore' } },
      { de: 'Opernhaus', en: 'Opera house', near: { de: 'Musical', en: 'Musical' } },
      {
        de: 'Weihnachtslied',
        en: 'Christmas carol',
        near: { de: 'Geburtstagslied', en: 'Birthday song' },
      },
      { de: 'Triangel', en: 'Triangle', near: { de: 'Tamburin', en: 'Tambourine' } },
      { de: 'Playback', en: 'Playback', near: { de: 'Autotune', en: 'Autotune' } },
      { de: 'Songcontest', en: 'Song contest', near: { de: 'Charts', en: 'Charts' } },
      { de: 'Ukulele', en: 'Ukulele', near: { de: 'Mandoline', en: 'Mandolin' } },
    ],
  },
]

export const CATEGORY_BY_ID = new Map(CATEGORIES.map((c) => [c.id, c]))
