/** A word is always a de/en pair so switching language never changes the round. */
export type Word = { de: string; en: string }

export type Category = {
  id: string
  name: Word
  emoji: string
  words: Word[]
}

export const CATEGORIES: Category[] = [
  {
    id: 'animals',
    emoji: '🦊',
    name: { de: 'Tiere', en: 'Animals' },
    words: [
      { de: 'Elefant', en: 'Elephant' },
      { de: 'Pinguin', en: 'Penguin' },
      { de: 'Krokodil', en: 'Crocodile' },
      { de: 'Eichhörnchen', en: 'Squirrel' },
      { de: 'Hai', en: 'Shark' },
      { de: 'Igel', en: 'Hedgehog' },
      { de: 'Kamel', en: 'Camel' },
      { de: 'Adler', en: 'Eagle' },
      { de: 'Qualle', en: 'Jellyfish' },
      { de: 'Fledermaus', en: 'Bat' },
      { de: 'Schnecke', en: 'Snail' },
      { de: 'Wolf', en: 'Wolf' },
      { de: 'Papagei', en: 'Parrot' },
      { de: 'Biene', en: 'Bee' },
      { de: 'Faultier', en: 'Sloth' },
      { de: 'Oktopus', en: 'Octopus' },
      { de: 'Pferd', en: 'Horse' },
      { de: 'Ameise', en: 'Ant' },
      { de: 'Eisbär', en: 'Polar bear' },
      { de: 'Frosch', en: 'Frog' },
    ],
  },
  {
    id: 'food',
    emoji: '🍕',
    name: { de: 'Essen & Trinken', en: 'Food & Drink' },
    words: [
      { de: 'Pizza', en: 'Pizza' },
      { de: 'Schnitzel', en: 'Schnitzel' },
      { de: 'Sushi', en: 'Sushi' },
      { de: 'Kaugummi', en: 'Chewing gum' },
      { de: 'Espresso', en: 'Espresso' },
      { de: 'Popcorn', en: 'Popcorn' },
      { de: 'Suppe', en: 'Soup' },
      { de: 'Senf', en: 'Mustard' },
      { de: 'Wassermelone', en: 'Watermelon' },
      { de: 'Käse', en: 'Cheese' },
      { de: 'Pommes', en: 'Fries' },
      { de: 'Honig', en: 'Honey' },
      { de: 'Zimt', en: 'Cinnamon' },
      { de: 'Bier', en: 'Beer' },
      { de: 'Spaghetti', en: 'Spaghetti' },
      { de: 'Erdbeere', en: 'Strawberry' },
      { de: 'Toastbrot', en: 'Toast' },
      { de: 'Chili', en: 'Chili' },
      { de: 'Eiswürfel', en: 'Ice cube' },
      { de: 'Apfelstrudel', en: 'Apple strudel' },
    ],
  },
  {
    id: 'sports',
    emoji: '⚽',
    name: { de: 'Sport', en: 'Sports' },
    words: [
      { de: 'Fußball', en: 'Football' },
      { de: 'Klettern', en: 'Climbing' },
      { de: 'Yoga', en: 'Yoga' },
      { de: 'Marathon', en: 'Marathon' },
      { de: 'Skifahren', en: 'Skiing' },
      { de: 'Boxen', en: 'Boxing' },
      { de: 'Tauchen', en: 'Diving' },
      { de: 'Golf', en: 'Golf' },
      { de: 'Turnen', en: 'Gymnastics' },
      { de: 'Radrennen', en: 'Bike race' },
      { de: 'Schach', en: 'Chess' },
      { de: 'Surfen', en: 'Surfing' },
      { de: 'Eishockey', en: 'Ice hockey' },
      { de: 'Tennis', en: 'Tennis' },
      { de: 'Bogenschießen', en: 'Archery' },
      { de: 'Handstand', en: 'Handstand' },
      { de: 'Stabhochsprung', en: 'Pole vault' },
      { de: 'Schiedsrichter', en: 'Referee' },
      { de: 'Trainingslager', en: 'Training camp' },
      { de: 'Hantel', en: 'Dumbbell' },
    ],
  },
  {
    id: 'screen',
    emoji: '🎬',
    name: { de: 'Filme & Serien', en: 'Movies & Shows' },
    words: [
      { de: 'Titanic', en: 'Titanic' },
      { de: 'Harry Potter', en: 'Harry Potter' },
      { de: 'Der Pate', en: 'The Godfather' },
      { de: 'Jurassic Park', en: 'Jurassic Park' },
      { de: 'Der König der Löwen', en: 'The Lion King' },
      { de: 'Matrix', en: 'The Matrix' },
      { de: 'Stranger Things', en: 'Stranger Things' },
      { de: 'Breaking Bad', en: 'Breaking Bad' },
      { de: 'Findet Nemo', en: 'Finding Nemo' },
      { de: 'James Bond', en: 'James Bond' },
      { de: 'Herr der Ringe', en: 'Lord of the Rings' },
      { de: 'Tatort', en: 'Crime scene show' },
      { de: 'Zurück in die Zukunft', en: 'Back to the Future' },
      { de: 'Game of Thrones', en: 'Game of Thrones' },
      { de: 'Shrek', en: 'Shrek' },
      { de: 'Star Wars', en: 'Star Wars' },
      { de: 'Die Simpsons', en: 'The Simpsons' },
      { de: 'Fluch der Karibik', en: 'Pirates of the Caribbean' },
      { de: 'Avatar', en: 'Avatar' },
      { de: 'Sissi', en: 'Sissi' },
    ],
  },
  {
    id: 'jobs',
    emoji: '👩‍🚒',
    name: { de: 'Berufe', en: 'Jobs' },
    words: [
      { de: 'Feuerwehrmann', en: 'Firefighter' },
      { de: 'Zahnarzt', en: 'Dentist' },
      { de: 'Pilot', en: 'Pilot' },
      { de: 'Bäcker', en: 'Baker' },
      { de: 'Lehrerin', en: 'Teacher' },
      { de: 'Influencer', en: 'Influencer' },
      { de: 'Tierarzt', en: 'Vet' },
      { de: 'Programmierer', en: 'Programmer' },
      { de: 'Fotografin', en: 'Photographer' },
      { de: 'Bauarbeiter', en: 'Construction worker' },
      { de: 'Kellner', en: 'Waiter' },
      { de: 'Bergführer', en: 'Mountain guide' },
      { de: 'Richterin', en: 'Judge' },
      { de: 'Astronaut', en: 'Astronaut' },
      { de: 'Friseur', en: 'Hairdresser' },
      { de: 'Müllabfuhr', en: 'Garbage collector' },
      { de: 'Physiotherapeut', en: 'Physiotherapist' },
      { de: 'Detektiv', en: 'Detective' },
      { de: 'Steuerberater', en: 'Tax advisor' },
      { de: 'Busfahrerin', en: 'Bus driver' },
    ],
  },
  {
    id: 'places',
    emoji: '🗺️',
    name: { de: 'Orte', en: 'Places' },
    words: [
      { de: 'Flughafen', en: 'Airport' },
      { de: 'Bibliothek', en: 'Library' },
      { de: 'Schwimmbad', en: 'Swimming pool' },
      { de: 'Friedhof', en: 'Cemetery' },
      { de: 'Supermarkt', en: 'Supermarket' },
      { de: 'Zahnarztpraxis', en: 'Dental practice' },
      { de: 'Baustelle', en: 'Construction site' },
      { de: 'Kino', en: 'Cinema' },
      { de: 'Wüste', en: 'Desert' },
      { de: 'Autobahn', en: 'Motorway' },
      { de: 'Dachboden', en: 'Attic' },
      { de: 'Zirkus', en: 'Circus' },
      { de: 'Bahnhof', en: 'Train station' },
      { de: 'Skihütte', en: 'Ski lodge' },
      { de: 'Gefängnis', en: 'Prison' },
      { de: 'Museum', en: 'Museum' },
      { de: 'Waschsalon', en: 'Laundromat' },
      { de: 'Leuchtturm', en: 'Lighthouse' },
      { de: 'Fitnessstudio', en: 'Gym' },
      { de: 'Weltraumstation', en: 'Space station' },
    ],
  },
  {
    id: 'objects',
    emoji: '🧦',
    name: { de: 'Alltag', en: 'Everyday Objects' },
    words: [
      { de: 'Regenschirm', en: 'Umbrella' },
      { de: 'Zahnbürste', en: 'Toothbrush' },
      { de: 'Staubsauger', en: 'Vacuum cleaner' },
      { de: 'Schlüsselbund', en: 'Keychain' },
      { de: 'Waschmaschine', en: 'Washing machine' },
      { de: 'Kopfhörer', en: 'Headphones' },
      { de: 'Klopapier', en: 'Toilet paper' },
      { de: 'Ladekabel', en: 'Charging cable' },
      { de: 'Kerze', en: 'Candle' },
      { de: 'Brille', en: 'Glasses' },
      { de: 'Wecker', en: 'Alarm clock' },
      { de: 'Socke', en: 'Sock' },
      { de: 'Geschirrspüler', en: 'Dishwasher' },
      { de: 'Leiter', en: 'Ladder' },
      { de: 'Spiegel', en: 'Mirror' },
      { de: 'Bügeleisen', en: 'Iron' },
      { de: 'Rucksack', en: 'Backpack' },
      { de: 'Taschenlampe', en: 'Flashlight' },
      { de: 'Schere', en: 'Scissors' },
      { de: 'Gießkanne', en: 'Watering can' },
    ],
  },
  {
    id: 'nature',
    emoji: '🌿',
    name: { de: 'Natur & Wetter', en: 'Nature & Weather' },
    words: [
      { de: 'Gewitter', en: 'Thunderstorm' },
      { de: 'Regenbogen', en: 'Rainbow' },
      { de: 'Vulkan', en: 'Volcano' },
      { de: 'Nebel', en: 'Fog' },
      { de: 'Lawine', en: 'Avalanche' },
      { de: 'Wasserfall', en: 'Waterfall' },
      { de: 'Sonnenuntergang', en: 'Sunset' },
      { de: 'Gletscher', en: 'Glacier' },
      { de: 'Sandstrand', en: 'Sandy beach' },
      { de: 'Hagel', en: 'Hail' },
      { de: 'Vollmond', en: 'Full moon' },
      { de: 'Dschungel', en: 'Jungle' },
      { de: 'Erdbeben', en: 'Earthquake' },
      { de: 'Tautropfen', en: 'Dewdrop' },
      { de: 'Nordlicht', en: 'Northern lights' },
      { de: 'Sumpf', en: 'Swamp' },
      { de: 'Höhle', en: 'Cave' },
      { de: 'Windstille', en: 'Dead calm' },
      { de: 'Waldbrand', en: 'Wildfire' },
      { de: 'Schneeflocke', en: 'Snowflake' },
    ],
  },
  {
    id: 'austria',
    emoji: '🏔️',
    name: { de: 'Österreich', en: 'Austria' },
    words: [
      { de: 'Sachertorte', en: 'Sachertorte' },
      { de: 'Lipizzaner', en: 'Lipizzaner horse' },
      { de: 'Wiener Riesenrad', en: 'Vienna Ferris wheel' },
      { de: 'Großglockner', en: 'Großglockner' },
      { de: 'Lederhose', en: 'Lederhosen' },
      { de: 'Almdudler', en: 'Almdudler' },
      { de: 'Schladming', en: 'Schladming' },
      { de: 'Mozartkugel', en: 'Mozart ball' },
      { de: 'Heuriger', en: 'Wine tavern' },
      { de: 'Kaiserschmarrn', en: 'Kaiserschmarrn' },
      { de: 'Wiener Linien', en: 'Vienna metro' },
      { de: 'Neujahrskonzert', en: 'New Year Concert' },
      { de: 'Krampus', en: 'Krampus' },
      { de: 'Wachau', en: 'Wachau valley' },
      { de: 'Skisprungschanze', en: 'Ski jump' },
      { de: 'Schönbrunn', en: 'Schönbrunn Palace' },
      { de: 'Marillenknödel', en: 'Apricot dumpling' },
      { de: 'Bundesheer', en: 'Austrian army' },
      { de: 'Kaffeehaus', en: 'Coffee house' },
      { de: 'Murinsel', en: 'Mur island' },
    ],
  },
  {
    id: 'music',
    emoji: '🎧',
    name: { de: 'Musik', en: 'Music' },
    words: [
      { de: 'Schlagzeug', en: 'Drum kit' },
      { de: 'Dudelsack', en: 'Bagpipes' },
      { de: 'Karaoke', en: 'Karaoke' },
      { de: 'Festival', en: 'Festival' },
      { de: 'Ohrwurm', en: 'Earworm' },
      { de: 'Chor', en: 'Choir' },
      { de: 'Techno', en: 'Techno' },
      { de: 'Geige', en: 'Violin' },
      { de: 'Plattenspieler', en: 'Record player' },
      { de: 'Blasmusik', en: 'Brass band' },
      { de: 'Rapbattle', en: 'Rap battle' },
      { de: 'Klavierstunde', en: 'Piano lesson' },
      { de: 'Kopfhörerkabel', en: 'Headphone cable' },
      { de: 'Gitarrensolo', en: 'Guitar solo' },
      { de: 'Opernhaus', en: 'Opera house' },
      { de: 'Weihnachtslied', en: 'Christmas carol' },
      { de: 'Triangel', en: 'Triangle' },
      { de: 'Playback', en: 'Playback' },
      { de: 'Songcontest', en: 'Song contest' },
      { de: 'Ukulele', en: 'Ukulele' },
    ],
  },
]

export const CATEGORY_BY_ID = new Map(CATEGORIES.map((c) => [c.id, c]))
